[package]
name = "hello_world"
version = "0.1.0"
authors = ["Michael Trojan Okoh <michael@okoh.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
